### ISSUE TITLE
Get info of file from torrent hash

### ISSUE THREAD

**Issue by the-rarbg** [Power2All/torrust-actix#28]
Any way to create api like this from tracker which give file info example:

https://tracker-info.mirrorbay.org/scrape/D71A9D5708A2F1D1F658492189F7F18D5E1FB6AB?fetchData=true

give info in json like:
{"announce":["udp://tracker.opentrackr.org:1337/announce"],"infoHash":"d71a9d5708a2f1d1f658492189f7f18d5e1fb6ab","complete":54,"downloaded":450,"incomplete":28,"name":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST","magnetURI":"magnet:?xt=urn:btih:d71a9d5708a2f1d1f658492189f7f18d5e1fb6ab&dn=Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce","files":[{"name":"2_eng.srt","size":5337,"path":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST/Subs/2_eng.srt"},{"name":"3_eng.srt","size":155365,"path":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST/Subs/3_eng.srt"},{"name":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST.mp4","size":2508444746,"path":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST/Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST.mp4"},{"name":"Encoded by KONTRAST.txt","size":1432,"path":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST/Encoded by KONTRAST.txt"},{"name":"[TGx]Downloaded from torrentgalaxy.to .txt","size":715,"path":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST/[TGx]Downloaded from torrentgalaxy.to .txt"}]}

**Comment by Power2All** [comment]
> Any way to create api like this from tracker which give file info example:
> 
> https://tracker-info.mirrorbay.org/scrape/D71A9D5708A2F1D1F658492189F7F18D5E1FB6AB?fetchData=true
> 
> give info in json like: {"announce":["udp://tracker.opentrackr.org:1337/announce"],"infoHash":"d71a9d5708a2f1d1f658492189f7f18d5e1fb6ab","complete":54,"downloaded":450,"incomplete":28,"name":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST","magnetURI":"magnet:?xt=urn:btih:d71a9d5708a2f1d1f658492189f7f18d5e1fb6ab&dn=Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce","files":[{"name":"2_eng.srt","size":5337,"path":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST/Subs/2_eng.srt"},{"name":"3_eng.srt","size":155365,"path":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST/Subs/3_eng.srt"},{"name":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST.mp4","size":2508444746,"path":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST/Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST.mp4"},{"name":"Encoded by KONTRAST.txt","size":1432,"path":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST/Encoded by KONTRAST.txt"},{"name":"[TGx]Downloaded from torrentgalaxy.to .txt","size":715,"path":"Blue.Beetle.2023.1080p.WEBRip.x265-KONTRAST/[TGx]Downloaded from torrentgalaxy.to .txt"}]}

Tracker is not made for handling torrent files.
The only thing that is tracked is the hash (no name), peers, seeders, and completed.
Naming and info of the torrent file is a whole separate project, nothing to do with this software.
