### ISSUE TITLE
Error SSL

### ISSUE THREAD

**Issue by ElManKO92** [Power2All/torrust-actix#35]
When i tried connect the api to php with cURL i have this response "SSL Certificate problem: unable to get local issuer", and in the browser all work fine, the response is like the example of the project page.

**Comment by Power2All** [comment]
Did you enable SSL setting ?
If not, then it's just HTTP without SSL.

**Comment by ElManKO92** [comment]
I did it, in fact I had to convert my key file with the help of openssl so that torrust-actix recognized it and did not give me an error when I executed it, as I told you in the browser it does not give an error and the lock appears correctly, when I try to connecting the API to php using cURL is when it gives that error

**Comment by Power2All** [comment]
There will be an option that Torrust-Actix will generate a self-signed certificate through an argument variable, will implement this with v4.0.0.

**Comment by Power2All** [comment]
Implemented for development usage.
Will still advice to use something like LetsEncrypt.
For now, you can simply use some arguments when starting the application to generate a simple self-signed certificate with optionally an domain name. By default "localhost" is accepted.
