### ISSUE TITLE
Allowing Dual Stack Peers (IPv4 and IPv6)

### ISSUE THREAD

**Issue by roridev** [Power2All/torrust-actix#36]
Is there a way to allow for a single peer to use both IPv4 and IPv6 so that other clients don't get alienated and can always find peers?

I've created two separate subdomains `tracker.****` and `tracker6.****`, the first only has a A DNS entry, while the last one only has an AAAA entry, to see if splitting the DNS query would lead to it accepting the broadcast on both IPv4 and IPv6. 

Accessing the API made me find only my IPv6 address, which means I wouldn't be able to seed to users with only IPv4 support, even though I added both tracker subdomains in the torrent.

**Comment by Power2All** [comment]
> Is there a way to allow for a single peer to use both IPv4 and IPv6 so that other clients don't get alienated and can always find peers?
> 
> I've created two separate subdomains `tracker.****` and `tracker6.****`, the first only has a A DNS entry, while the last one only has an AAAA entry, to see if splitting the DNS query would lead to it accepting the broadcast on both IPv4 and IPv6.
> 
> Accessing the API made me find only my IPv6 address, which means I wouldn't be able to seed to users with only IPv4 support, even though I added both tracker subdomains in the torrent.

This is an client thing, not a tracker thing.
As far as I'm aware, you need to make it so that the tracker announcements are "separate", and not in a fallback group.

**Comment by Power2All** [comment]
> Is there a way to allow for a single peer to use both IPv4 and IPv6 so that other clients don't get alienated and can always find peers?
> 
> I've created two separate subdomains `tracker.****` and `tracker6.****`, the first only has a A DNS entry, while the last one only has an AAAA entry, to see if splitting the DNS query would lead to it accepting the broadcast on both IPv4 and IPv6.
> 
> Accessing the API made me find only my IPv6 address, which means I wouldn't be able to seed to users with only IPv4 support, even though I added both tracker subdomains in the torrent.



As an update on what I posted, IPv4/IPv6 dualstack doesn't work on UDP, possibly only on HTTP, but it's not ISO (has no BEP), so it won't be implemented. IPv4 and IPv6 aren't inter-exchangeable.
